# SPDX-FileCopyrightText: 1998 Argonne National Laboratory
#
# SPDX-License-Identifier: EPICS

TOP = ../..
include $(TOP)/configure/CONFIG
DB += test02.db
DB += test01.db


include $(TOP)/configure/RULES
# ----------------------------------------
# ADD RULES AFTER THIS LINE
